package supervisedLearning.linearRegression.observationBroadener
import breeze.linalg.DenseVector

/**
  * An observation broadener that raises an existing dimension of an observation to some power and adds it to the
  * observation as a new dimension.
  *
  * @param index an integer denoting which dimension of an observation should be used as a basis for new dimension creation
  * @param power the power used to generate the new dimension
  */
class AddRaisedDimension(override val index: Int, private val power: Double) extends ObservationDimensionsExtender(index) {
	
	/**
	  * Given an observation, extend it by adding a new dimension generated by taking the dimension indexed by index
	  * and raising it by a power.
	  *
	  * @param observation an observation to which we would like to add a dimension
	  * @return the extended observation
	  */
	override def getExtendedObservation(observation: DenseVector[Double]): DenseVector[Double] = {
		
		if (super.isIndexOutOfBounds(observation)) {
			return observation
		}
		
		val newDimensionValue = scala.math.pow(observation(index), power)
		super.extendObservation(observation, newDimensionValue)
	}
}
